CREATE TABLE users(userId VARCHAR(255) PRIMARY KEY NOT NULL,
 firstname VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL , 
phoneNumber VARCHAR(100) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL,
 createdAt DATETIME NOT NULL)

 SELECT * FROM users;

 ALTER TABLE users ADD image VARCHAR(255);