### Create Event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventName": "Sample Event del",
  "location": "Sample Location del",
  "eventDate": "2024-08-01",
  "eventTime": "12:00 PM",  
  "description": "This is a sample event description.",
  "image": "https://i.pinimg.com/474x/bd/ad/7c/bdad7c93a87d4dfc82080fb299e1759b.jpg"
}

### Get All Events
GET http://localhost:3000/api/events

### Get Event By Id
GET http://localhost:3000/api/events/829A82E1-0C06-4038-8E85-18536747716E

### Update Event
PUT http://localhost:3000/api/events/829A82E1-0C06-4038-8E85-18536747716E
Content-Type: application/json

{
  "eventName": "Updated Event Name",
  "location": "Updated Location",
  "eventDate": "2024-08-02",
  "eventTime": "02:30 PM",  
  "description": "This is an updated event description."
}

### Delete Event
DELETE http://localhost:3000/api/events/A46E64FC-F931-4022-AEA4-6F45DDC6085A
