### Create Event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventName": "Sample Event del",
  "location": "Sample Location del",
  "eventDate": "2024-08-01",
  "eventTime": "12:00 PM",  
  "description": "This is a sample event description.",
  "image": "https://i.pinimg.com/474x/bd/ad/7c/bdad7c93a87d4dfc82080fb299e1759b.jpg"
}

### Get All Events
GET http://localhost:3000/api/events

### Get Event By Id
GET http://localhost:3000/api/events/829A82E1-0C06-4038-8E85-18536747716E

### Update Event
PUT http://localhost:3000/api/events/D3E0BF6B-E935-40BA-98D0-4B903F601908
Content-Type: application/json

{
  "eventName": "Art Event",
  "location": "Nairobi Gallery",
  "eventDate": "2024-08-02",
  "eventTime": "02:30 PM",  
  "description": "Art that touches the Heart",
  "image": "https://i.pinimg.com/474x/4f/78/a2/4f78a2ac80a385cc2c40e2d633439df7.jpg"
}

### Delete Event
DELETE http://localhost:3000/api/events/D3E0BF6B-E935-40BA-98D0-4B903F601908
