# Create a new promotion
POST http://localhost:3000/api/promotions
Content-Type: application/json

{
  "name": "Winter Sale delete",
  "type": "Buy One Get One Free",
  "discountAmount": 0.00,
  "startDate": "2024-12-01",
  "endDate": "2024-12-31"
}

### Get all promotions
GET http://localhost:3000/api/promotions

### Get a specific promotion by ID
GET http://localhost:3000/api/promotions/dad14539-1190-4c15-ab1b-b94195db56e1

### Update a specific promotion by ID
PUT http://localhost:3000/api/promotions/dad14539-1190-4c15-ab1b-b94195db56e1
Content-Type: application/json

{
  "name": "Winter Sale",
  "type": "Percentage",
  "discountAmount": 30.00,
  "startDate": "2024-12-01",
  "endDate": "2024-12-31"
}

### Delete a specific promotion by ID
DELETE http://localhost:3000/api/promotions/dad14539-1190-4c15-ab1b-b94195db56e1

