### Create a new ticket
POST http://localhost:3000/api/tickets/create
Content-Type: application/json

{
  "userId": "C78275A7-C952-4005-93C0-99F36EC3F813",
  "eventId": "D3E0BF6B-E935-40BA-98D0-4B903F601908",
  "type": "couple",
  "numberOfTickets": 2,
  "price": 100.00,
  "status": "active"
}


### Get all tickets
GET http://localhost:3000/api/tickets

### Get a single ticket by ID
GET http://localhost:3000/api/tickets/

### Update a ticket
PUT http://localhost:3000/api/tickets/update/
Content-Type: application/json

{
  "numberOfTickets": 4,
  "price": 180.00,
  "status": "confirmed"
}

### Delete a ticket
DELETE http://localhost:3000/api/tickets/
