### Create a new ticket
POST http://localhost:3000/api/tickets/create
Content-Type: application/json

{
  "userId": "6B2AA3DE-9C7C-490A-AE53-4F0E25182895",
  "eventId": "CC8A18BC-9AF7-4BAA-8FE5-0507F419C0DE",
  "type": "couple",
  "numberOfTickets": 1
}


### Get all tickets
GET http://localhost:3000/api/tickets

### Get a single ticket by ID
GET http://localhost:3000/api/tickets/B0AB9E21-634B-424B-8589-E3C05B0292DD

### Fetch Tickets by User ID
GET http://localhost:3000/api/tickets/user/6B2AA3DE-9C7C-490A-AE53-4F0E25182895
Content-Type: application/json

### Fetch Tickets by Event ID
GET http://localhost:3000/api/tickets/event/CC8A18BC-9AF7-4BAA-8FE5-0507F419C0DE
Content-Type: application/json


### Update a ticket
PUT http://localhost:3000/api/tickets/update/B0AB9E21-634B-424B-8589-E3C05B0292DD
Content-Type: application/json

{
  "numberOfTickets": 4,
  "status": "cancelled"
}

### Delete a ticket
DELETE http://localhost:3000/api/tickets/D9318216-AF02-48C2-AFB0-A1117C40CE7F

### Get Ticket Summary by Event ID
GET http://localhost:3000/api/tickets/summary/CC8A18BC-9AF7-4BAA-8FE5-0507F419C0DE
Accept: application/json
Content-Type: application/json

