### Create a new ticket
POST http://localhost:3000/api/tickets/create
Content-Type: application/json

{
  "userId": "C78275A7-C952-4005-93C0-99F36EC3F813",
  "eventId": "CC8A18BC-9AF7-4BAA-8FE5-0507F419C0DE",
  "type": "couple",
  "numberOfTickets": 8
}


### Get all tickets
GET http://localhost:3000/api/tickets

### Get a single ticket by ID
GET http://localhost:3000/api/tickets/B0AB9E21-634B-424B-8589-E3C05B0292DD

### Fetch Tickets by User ID
GET http://localhost:3000/api/tickets/user/C78275A7-C952-4005-93C0-99F36EC3F813
Content-Type: application/json

### Fetch Tickets by Event ID
GET http://localhost:3000/api/tickets/event/CC8A18BC-9AF7-4BAA-8FE5-0507F419C0DE
Content-Type: application/json


### Update a ticket
PUT http://localhost:3000/api/tickets/update/B0AB9E21-634B-424B-8589-E3C05B0292DD
Content-Type: application/json

{
  "numberOfTickets": 4,
  "status": "cancelled"
}

### Delete a ticket
DELETE http://localhost:3000/api/tickets/2C76E144-2998-46AF-9845-AE6AF0ACDEF0

### Get Ticket Summary by Event ID
GET http://localhost:3000/api/tickets/summary/CC8A18BC-9AF7-4BAA-8FE5-0507F419C0DE
Accept: application/json
Content-Type: application/json

