### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstname": "olCar del",
  "lastname": "Martin",
  "phoneNumber": "0111997539",
  "email": "carolmartoz2863@gmail.com",
  "password": "password123",
  "image": "https://i.pinimg.com/474x/be/25/7d/be257dad70a18e830f560de0887d8bd1.jpg"
}

### Login User 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "carolmartoz2863@gmail.com",
  "password": "password123"
}

### Update User
PUT http://localhost:3000/api/users/update
Content-Type: application/json

{
  "userId": "A3944C13-999F-4949-9625-FBB0A8352DDE",
  "firstname": "Updated Firstname",
  "lastname": "Updated Lastname",
  "phoneNumber": "0740837669",
  "email": "updated@example.com",
  "password": "password123"
}

### Delete User
DELETE http://localhost:3000/api/users/68C6AA4D-8A80-48A5-A37C-97FC841F6A44

### Get All Users
GET http://localhost:3000/api/users

### Get User by ID
GET http://localhost:3000/api/users/A3944C13-999F-4949-9625-FBB0A8352DDE

