### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstname": "olCar del",
  "lastname": "Martin",
  "phoneNumber": "0111997539",
  "email": "carolmartoz2863@gmail.com",
  "password": "password123",
  "image": "https://i.pinimg.com/474x/be/25/7d/be257dad70a18e830f560de0887d8bd1.jpg"
}

### Login User 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "carolmartoz2863@gmail.com",
  "password": "password123"
}

### Update User
PUT http://localhost:3000/api/users/update
Content-Type: application/json

{
  "userId": "561A955A-345D-4CA9-8DFC-B0C178CB92A0",
  "firstname": "Updated Firstname",
  "lastname": "Updated Lastname",
  "phoneNumber": "0740837669",
  "email": "carolmartoz1063@gmail.com",
  "password": "password123"
}

### Delete User
DELETE http://localhost:3000/api/users/561A955A-345D-4CA9-8DFC-B0C178CB92A0

### Get All Users
GET http://localhost:3000/api/users

### Get User by ID
GET http://localhost:3000/api/users/F80B51D3-24BD-4F26-8886-321ECF6F95E1

