### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstname": "olCar del",
  "lastname": "Martin",
  "phoneNumber": "0111997539",
  "email": "carolmartoz263@gmail.com",
  "password": "password123"
}

### Login User 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "carolmartoz2863@gmail.com",
  "password": "password123"
}

### Update User
PUT http://localhost:3000/api/users/update
Content-Type: application/json

{
  "userId": "A3944C13-999F-4949-9625-FBB0A8352DDE",
  "firstname": "Updated Firstname",
  "lastname": "Updated Lastname",
  "phoneNumber": "0740837669",
  "email": "updated@example.com",
  "password": "password123"
}

### Delete User
DELETE http://localhost:3000/api/users/4EB2985D-EE55-48C7-8F81-CFD2D223F65C

### Get All Users
GET http://localhost:3000/api/users

### Get User by ID
GET http://localhost:3000/api/users/A3944C13-999F-4949-9625-FBB0A8352DDE

